import './global.css';

export const metadata = {
  title: 'Welcome to demo2',
  description: 'Generated by create-nx-workspace',
};

const fetchData = async () => {
  return await (
    await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/hello`, {
      cache: 'no-store',
    })
  ).text();
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data = await fetchData();

  console.log(data);
  return (
    <html lang="en">
      <body>
        {data}
        {children}
      </body>
    </html>
  );
}
